
# kubectl create secret generic azure-secret \
#--from-literal azurestorageaccountname=NAME \
#--from-literal azurestorageaccountkey="KEY" --type=Opaque
# You can use default storage class or create a custom one
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: customAzureFile
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
parameters:
  storageAccount: your_storage_accounr
  skuName: Standard_LRS  
#available values: Standard_LRS, Standard_GRS,  Premium_LRS, Premium_ZRS etc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-custom
  labels:
    usage: pv-custom
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: customAzureFile
  azureFile:
    secretName: azure-secret
    shareName: azure-secret-share
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
# PVC

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: custom-pvc
  labels:
    usage: pvc-custom
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      usage: pv-custom
  resources:
    requests:
      storage: 10Gi
  volumeName: vol1
  storageClassName: customAzureFile
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
---
