
# kubectl create secret generic azure-secret \
#--from-literal azurestorageaccountname=NAME \
#--from-literal azurestorageaccountkey="KEY" --type=Opaque
# You can use default storage class or create a custom one
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: customAzureFile
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
parameters:
  storageAccount: your_storage_accounr
  skuName: Standard_LRS  
#available values: Standard_LRS, Standard_GRS,  Premium_LRS, Premium_ZRS etc

---
# PVC

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: customAzureFile
---
